project_name: tl

version: 2

builds:
  - id: tl
    binary: tl
    ldflags:
      - -extldflags '-static' -X github.com/previousnext/tl-go/cmd.version={{.Version}}
    env:
      - CGO_ENABLED=0
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]
    goamd64: [ v3 ]

archives:
  - id: nix
    ids: [ tl ]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
    formats: tar.gz

release:
  prerelease: auto
  name_template: "TL {{.Version}}"
  github:
    owner: previousnext
    name: tl-go

nfpms:
  - ids: [ tl ]
    license: GPL-2.0
    maintainer: PreviousNext
    homepage: https://www.previousnext.com.au
    description: Command line time logger for Jira
    formats: [ deb, rpm ]
