name: 🏗️ Build

on:
  pull_request: ~
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v7

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install

      - name: 🧹 Lint
        run: |
          mise run lint

      - name: 🧪 Test
        run: |
          mise run test
